// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "config.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_config_2eproto() {
  delete ConfigDefine::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_config_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_config_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ConfigDefine::default_instance_ = new ConfigDefine();
  ConfigDefine::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_config_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_config_2eproto_once_);
void protobuf_AddDesc_config_2eproto() {
  ::google::protobuf::::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_config_2eproto_once_,
                 &protobuf_AddDesc_config_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_config_2eproto {
  StaticDescriptorInitializer_config_2eproto() {
    protobuf_AddDesc_config_2eproto();
  }
} static_descriptor_initializer_config_2eproto_;
#endif

// ===================================================================

bool ConfigDefine_ATTR_CONFIG_IsValid(int value) {
  switch(value) {
    case 100:
    case 1000:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ConfigDefine_ATTR_CONFIG ConfigDefine::DEF_FACTOR;
const ConfigDefine_ATTR_CONFIG ConfigDefine::RATE_BASE;
const ConfigDefine_ATTR_CONFIG ConfigDefine::ATTR_CONFIG_MIN;
const ConfigDefine_ATTR_CONFIG ConfigDefine::ATTR_CONFIG_MAX;
const int ConfigDefine::ATTR_CONFIG_ARRAYSIZE;
#endif  // _MSC_VER
bool ConfigDefine_VAL_TYPE_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ConfigDefine_VAL_TYPE ConfigDefine::VAL_TYPE_STRING;
const ConfigDefine_VAL_TYPE ConfigDefine::VAL_TYPE_INT32;
const ConfigDefine_VAL_TYPE ConfigDefine::VAL_TYPE_INT64;
const ConfigDefine_VAL_TYPE ConfigDefine::VAL_TYPE_MIN;
const ConfigDefine_VAL_TYPE ConfigDefine::VAL_TYPE_MAX;
const int ConfigDefine::VAL_TYPE_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
#endif  // !_MSC_VER

ConfigDefine::ConfigDefine()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void ConfigDefine::InitAsDefaultInstance() {
}

ConfigDefine::ConfigDefine(const ConfigDefine& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void ConfigDefine::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ConfigDefine::~ConfigDefine() {
  SharedDtor();
}

void ConfigDefine::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void ConfigDefine::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ConfigDefine& ConfigDefine::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_config_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_config_2eproto();
#endif
  return *default_instance_;
}

ConfigDefine* ConfigDefine::default_instance_ = NULL;

ConfigDefine* ConfigDefine::New() const {
  return new ConfigDefine;
}

void ConfigDefine::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool ConfigDefine::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
  return true;
#undef DO_
}

void ConfigDefine::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
}

int ConfigDefine::ByteSize() const {
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ConfigDefine::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const ConfigDefine*>(&from));
}

void ConfigDefine::MergeFrom(const ConfigDefine& from) {
  GOOGLE_CHECK_NE(&from, this);
}

void ConfigDefine::CopyFrom(const ConfigDefine& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConfigDefine::IsInitialized() const {

  return true;
}

void ConfigDefine::Swap(ConfigDefine* other) {
  if (other != this) {
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string ConfigDefine::GetTypeName() const {
  return "ConfigDefine";
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
