// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pve.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pve.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PveInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PveInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_pve_2eproto() {
  protobuf_AddDesc_pve_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "pve.proto");
  GOOGLE_CHECK(file != NULL);
  PveInfo_descriptor_ = file->message_type(0);
  static const int PveInfo_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PveInfo, curmap_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PveInfo, curbattle_),
  };
  PveInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PveInfo_descriptor_,
      PveInfo::default_instance_,
      PveInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PveInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PveInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PveInfo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_pve_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PveInfo_descriptor_, &PveInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_pve_2eproto() {
  delete PveInfo::default_instance_;
  delete PveInfo_reflection_;
}

void protobuf_AddDesc_pve_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tpve.proto\",\n\007PveInfo\022\016\n\006curmap\030\001 \001(\005\022\021"
    "\n\tcurbattle\030\002 \001(\005", 57);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pve.proto", &protobuf_RegisterTypes);
  PveInfo::default_instance_ = new PveInfo();
  PveInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pve_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pve_2eproto {
  StaticDescriptorInitializer_pve_2eproto() {
    protobuf_AddDesc_pve_2eproto();
  }
} static_descriptor_initializer_pve_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PveInfo::kCurmapFieldNumber;
const int PveInfo::kCurbattleFieldNumber;
#endif  // !_MSC_VER

PveInfo::PveInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PveInfo::InitAsDefaultInstance() {
}

PveInfo::PveInfo(const PveInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PveInfo::SharedCtor() {
  _cached_size_ = 0;
  curmap_ = 0;
  curbattle_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PveInfo::~PveInfo() {
  SharedDtor();
}

void PveInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PveInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PveInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PveInfo_descriptor_;
}

const PveInfo& PveInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_pve_2eproto();
  return *default_instance_;
}

PveInfo* PveInfo::default_instance_ = NULL;

PveInfo* PveInfo::New() const {
  return new PveInfo;
}

void PveInfo::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    curmap_ = 0;
    curbattle_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PveInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 curmap = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &curmap_)));
          set_has_curmap();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_curbattle;
        break;
      }

      // optional int32 curbattle = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_curbattle:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &curbattle_)));
          set_has_curbattle();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PveInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 curmap = 1;
  if (has_curmap()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->curmap(), output);
  }

  // optional int32 curbattle = 2;
  if (has_curbattle()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->curbattle(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PveInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 curmap = 1;
  if (has_curmap()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->curmap(), target);
  }

  // optional int32 curbattle = 2;
  if (has_curbattle()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->curbattle(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PveInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 curmap = 1;
    if (has_curmap()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->curmap());
    }

    // optional int32 curbattle = 2;
    if (has_curbattle()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->curbattle());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PveInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PveInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PveInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PveInfo::MergeFrom(const PveInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_curmap()) {
      set_curmap(from.curmap());
    }
    if (from.has_curbattle()) {
      set_curbattle(from.curbattle());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PveInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PveInfo::CopyFrom(const PveInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PveInfo::IsInitialized() const {

  return true;
}

void PveInfo::Swap(PveInfo* other) {
  if (other != this) {
    std::swap(curmap_, other->curmap_);
    std::swap(curbattle_, other->curbattle_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PveInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PveInfo_descriptor_;
  metadata.reflection = PveInfo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
